# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b713929efe4024d1e4306dd169feb7b1a31dac2a858ff1993749fdc58055b448085b68ab4b35d596e3ca12d25aaa90c57b53993c9ee9dd2f919d08c86221eafb

test:
  secret_key_base: ff4ba9b1c9e601a85064f4b6495da418d08748f859e2e114f850145e2a9638c97129128b7349ff016ee8712e21f376ba065948c5c4e8f003fcb0bcb951304c4e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
